step-runner-config:
    global-defaults:
        container-registries:
            registry.redhat.io:
                password: ENC[AES256_GCM,data:IBuoy8hZx1pjsgyiE+gVsmggx5gS5ZSLIlpt9Dj08g8i+UTy0QV7HmEynrUsqfuqzlT+Tv6GwuQ5Zux+VSmHRx3vLxJBiOmLAODHldPXlb8iNUi5Q15Hbk1w2Nj7rMwNkxe6dLDeHA8MovJCzibycDGx9lwYs8WjjD+/WYDY2WGBblvOlA7O0j5K+Ef1LhJqdbRpK83SncY372+BlWk03g7eEazPRYNZCVv6S87aVi7FhcLYBRGyRpjyqjUlKUap3WGOq7aRN82B8YNV456U5xTNkSkSvQnRcMVeEGTg5j00d7sA4NkwNQB6+vCx2p9P7AA/4Yvn2qUdgAxdno1gJM73eAhd3KGgPbL1d54PH8l7Z9Xn0ZR4QyUUOXKRiqoMB3EXNfL7GhTA7wTg3ppw+a52X49IWFL6hvK4qxXMhlXRYb8JiVtmsFCuh9LiRKfuW6we/tGvC7EZMfC+KHZIWhzd3y4piU4XIkQc8E+/R/unoAcnU09whTQpQMoBIIh6ifmRUZH/ek7+iPBOyQv08yuD9CTWAGEUeUzto4QL+7ZPq6vta6N+1eCtSI1XWuaoaVJ3VVeovdm3bJ3tZ6vZ2pshD21pY406w72gIgM/CRtAJRhtjqa1CxeuwRCQGQ/uoWqX3euwrBRHuDYH85a9VLU7c39f0NPVvlbQcdWst2qQ6xfLa/+sTgOCxnXES6HEBFBvUK/yhxpd6EyIodrF3WAt4T7t89uccihnf4ZoZS9So8jLFGi3VGa7PF9yDSpu26AkrfhLymIZfz1NoeyhcnHT2Yr9uzJUgX24aTXcD1X6ej4UD8qvDakrNbETdyWoWAVmJvdBU0hDBihDtaRVgw3W97g6eWBhYObFUMYfNDosp1D1JRO6tq8n4ynhF5+TV+8XhkQHPJcDGVgJVn6j2E73y/TRTD9SE6fdznMLJLTl0tu9E7filsGwT0o9xCeQPpDz9wr6Zpr9rQ5ggfTuq1egL6Eq+PowARr9NaStql+HWVj6JLOUoJQ=,iv:CToBAR7LCzZFLWBYxlwKxRHjFeJCO11DHqZAgWKY6ZM=,tag:NuiguiHlOB8GoaHNB7nB3A==,type:str]
            quay-quay-enterprise.apps.tssc.rht-set.com:
                password: ENC[AES256_GCM,data:lC2xXbK8EFLvrZt4tKR1yys9YNE046YvQf7ZT7T6K+3zWc9slOqE0B0fQBzaHEb32gkUGCS8WG2oYNIEyrKomg==,iv:ybic1Pe0pmaiDlYzZL3wcWqmgY0rHIGv6aZeo2AfC78=,tag:wCAL0Tp5T32jhv5hdNsRmQ==,type:str]
        maven-servers:
            internal-mirror:
                password: ENC[AES256_GCM,data:ea5YR17O5GJwp20pjqARcZlh,iv:IxYdTRjp79l8pVX2VnffXoo1pVp/Stbp4+5Ot8jB7Q4=,tag:9TplwieNQvwETAkqU89xHA==,type:str]
    tag-source:
    -   implementer: Git
        config:
            git-password: ENC[AES256_GCM,data:+1rCnKlhkMkR8n2t,iv:RaTfe/DyTH9SqQUFoZ9O5Hdl0HGQ3YT8LKuTyRyC3wM=,tag:BtcAcww4Nv/S3nkmrjvs6g==,type:str]
    static-code-analysis:
    -   implementer: SonarQube
        config:
            password: ENC[AES256_GCM,data:ezKV+c8eEN1hlC0T7jkZqHeS,iv:IUsyBh9kD1ME3UM2r8xKarHnP9ml9hcG/+rM0STxTFA=,tag:Du/2cdqPI6fJU4ABUVpVww==,type:str]
    deploy:
    -   implementer: ArgoCD
        config:
            argocd-password: ENC[AES256_GCM,data:tSWM7mSA,iv:C0uuG7Qcq0APBWQ1h9vc+bG3uIyCpKDarv+VIaTVNXM=,tag:mTZo833U8kavmp+VrllNmQ==,type:str]
            git-password: ENC[AES256_GCM,data:viUf3zoflH5d56BY,iv:6lh2/+sT1wi/g2k0mCFAF0AmNH/YPMkIoxlBgGrAfQw=,tag:0h10GTbGIBZK2If+vRFpEw==,type:str]
    report:
    -   implementer: ResultArtifactsArchive
        config:
            results-archive-destination-password: ENC[AES256_GCM,data:7jbKVak1Wk1/D4l0VtMejCj2,iv:/YLeh8aO7z6hEGaFTHgyyFpSsFbr9aB23botWwe9qrs=,tag:6AcjlHAx1TLoPdRO8HCjfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-06-30T11:58:20Z'
    mac: ENC[AES256_GCM,data:2EIMfYMQo9FpF19Qb8HE/UhrzlDv494KUHVWcG7TTHVwKNuBAds0OsO0VSWpg95bmQygihVpjPB7lNbNm/nZsVVnRJi6/SnJvUWdj1c1LPl+YAvlPfkgfEinNM0RMg4u7u3rTvB06nXT2cwnoRMr8h33SUk6OXXVz9zj40miak4=,iv:6pKv1QOIEX01hdGyfZFseVUd3ZhPx+LPKM2m3i5a/FM=,tag:9jUfZBefxfVj+lecA0eYbg==,type:str]
    pgp:
    -   created_at: '2020-09-28T12:23:20Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3GO6GKnGxytAQf/bOmh101rUks66ThdFfKWl1speOyuwUSm007oRXUmu6nb
            COKXfebAG6+7UYTMPWlnGlRjFW+TQAfPq77k6PqRr89O7a8J8LelmjOMV9RShi2G
            CxkmcgHEEwqcL9hjwuW1jAsMClj0eY4V8bDUKcp8V3jgDhgYUgA/HqNwh7ixEAl9
            K4W1NBb7opfemYUdSdwime9FXJUpCVGBD6WfLGcEKOTAlxZeSwW1S7pR32biDWBg
            3SPDTvD2/ro8GlCBgdMLYN9RcUer9wD51U+NZpL1J7B9KShJ+FkTwwrMQ/sLK1vT
            n6EWlocEIGi/FNiZlb1JgIyXrUXQCLfKcX4SGjCtq9JeAf6KrqWhKT+zOLiWKq6f
            4lgT+0iRNRl7VsVJ+/RSaITvsLGyekSkmXAccrdwFzjH4lBREbIpCsGcq2EqaKud
            0TVeH+3klv/cgqN/HGC15jceZGri7Zz8WpgIcxgiBQ==
            =5Tm3
            -----END PGP MESSAGE-----
        fp: 7EFB417E546C45EE36EE43F0DD2047E4342B2EBA
    -   created_at: '2020-09-28T12:28:18Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/pHJVB+8SuwAQ//Z529uMEhl31yyWiYFy78/qSdiyqOezwQCVB20ANFyDgD
            YASpoFOsFvsZU6ISIPQAfSYr1hudThlcug+AEov7LzYwafEGkNVxWfjxnk5OFdpa
            sgTUHjW5FECrpUGfL48zFqYyOQNXMp8YelGmXbVSP3LvO0Lz49dqWWhc/sFqQhPi
            68nXS5iz9VpzhB+cTDO32aa4gwfKg5aPz2mDli0EnvDXWOxNteT6g/iSB7mc9cHo
            vQMtyOxgzjy7apsUN4scAu1h0NFdSN711n4Pw51CRuYHQlbmkzIyWfcNqfEE4MoU
            +WWL9as5BtE50jAamDwNcvuoweWy8eAy6znvpLOxhKwLWu7fOQGvfg8jrgqXfMuk
            OSVrKkrC+aNA+T448KIVUaDfUBBuD6EtgDni5C12LqJs4QOSDrNu2lz9RHNwoXbu
            ENUdGEAoTABMgM3Vwwq7WzCcdqqM0/SskTYVNoa+zkG4DxVJoVpy6l9SrGF5Z5HD
            nL+ebIuA6fe7cNHthKuzbsxzlZTq5d/uJIqB5RL+IBJRIYO8Q+6+T948avoCZMk9
            otzo5ghau46iCDDd9Cr5PR2czLVzVRFXpcb4LyHFUJuqQjh6e82LoCbJGhRzgXLJ
            LdK2+5mxD3Gs5VY7wAJNsnvACpHlU/kIy2/yWd0H6p9PG582Pp/uaPFdaJYWYVvS
            XgHHUgnT/juxEKU8hDgLWt8K59jnBEfjSPG/4ELZUUwk4ii7v7aVgBMkkMg2ybtG
            gwCDNsA9WDt2s9m21z7i0ek1mywqzuze4FvPooi/Fg0U42mHGTRHjt7yZZvaZW4=
            =BNQ4
            -----END PGP MESSAGE-----
        fp: 355C11B55E83B15E5CF6366283637FAF9D7905E1
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/JEnAHZDjB7AQgAlwpfhNDNv+1b8y+4uMaV3U+i+4y/feUN46HdIKw4Hcet
            yvcs1cV/e7V2yYxNfzZfJ1K9jBcuLC83UStey6sn+OsDiIDykcl8DcU76EUR8iHG
            7h+Vqz3BXU9NEnm9RfOeE8vH+tIaZKn7tNORCDqRjqK8oReT6gGw7a5BkkWzsWrR
            w+xnn8ATEtINQYi7SCFxQvq+8dSXS3uXvAKMjGFQk3r4Ls6SWOQl0Ly2JDJ/z/kS
            vrUhuj82YMhoZ8box5MFOIhnWSyHHz2FW5XsgjvATvm5VpA2XiHDs4bZumK/0CiL
            l5JN2QYWWbkdALMahkqnZ04R+j/W2eT1+5eRf2BdbdJeATCoHqes5dsiIAZ+aL40
            lhp3HGdLdz4NWLXVxPpy6bXAJKxeJ7dLHpuBgyIvqsBQpdrYCs9xEu/yvYpRHYMb
            LKSRgezuWQAGZ50Dd0HdtgECMWWVc8tHuXHYyZ0XlQ==
            =xH3z
            -----END PGP MESSAGE-----
        fp: 2A25DA15018235A6206921952730D7A70EC35190
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6220UozeaaQAQ//QtqZAx1pe4hPqNRnikTQyv8d/N89SgXdMSP0fs5jP8Vs
            4lQXJrQ5CVl4i3Pk/URC3kuZEXlcAAfjKeY9VhlX2mRrf3FR7YDeEeE6rnQ+EwLW
            4oja8+SgOimkxE3vn9DwtczdaVzPcB2EhEuD0vVCKjOAoOFv3I1IsVZrvE2vpQyf
            vQoTJvEoB2CoWo88XGzqTZjE1CoOo8qR/xHDxAXvYk9D1ywNpegEKLdjeDj8h5M6
            btOZRv2bzSu5rKDmW7yJBXFkNzUsstl5u5NbZc0segSvDOIIiKY4eZKY9nigHc8/
            4Eo5EmvnOii4D8Nw5mPEB6NmY0TAnkAYolvSVVEVD3yh1Pf/Nrfl3YDNCUMdRMa3
            iV2cevwJS2lyJdXSHLGxtyLYjWMf2wDhPLFc71J7I+FHk3yeHQRyYe7SbYTWA4QW
            Zfn1jxVnvGMCSVtEPnElifQKAnDi76H+nb/yEkH2ECk1b3Ui51sVRPONDvLn2UO9
            WmOFQ8Uu1YqZkkXWBLU7lBxCe44eO3RopgpJIRdEKjy7p6qYRhLuFHpNYBEqhEVX
            8PVhGddV/qCt6UW95/1hBDrz3ARquQJ6Uw10+xg+vh5efgPnaWfaq0ADHZOESIiC
            EKAt0y1eH/MspXx0dcuMVZNL84Pr04FQB4laMHFwAm/g2dAW2rpA3At/wvHFrD/S
            XgH1ggH+mZdecqKBHpqE3YfR3+m6TcSbmcu4A2NpFVHnY85iNjPa2YTCTWrAervw
            yryPAxt4ykkmRhh02A4kQ7mW7zs9bp2mUocAZw+GGIwNS3OXDCKD1WlU92nV3Zg=
            =zxW8
            -----END PGP MESSAGE-----
        fp: DA7B00C8ACAFED2DA7E33D1ADFA8C968E1F69B13
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA75NWiDtWcDHAQ/+Kl6rkZgnZqzEg5mPFT/S6UUX5X5QdWHDgOU29If7q8vI
            Xr8uloX3ZiD7I+6L2JWSTIFMLhK3CZzxxl36dD7cmAGCQeZD5tWdNAFjLg+lcbp2
            6BxPzgz7LyJLVbJ1m78oRljqz5CzY6U+sSGSDwpTbEV56U8fId2oKnCRaQ5BbeaS
            ZQouSDFr5jhjge3ZeVikg+3Ts1CtCQyb8zx+RZRzOg+25dZytOrlVoRM2zbvTfhd
            OIDSYIfuUCJGACzRUT1FfMcX4+6wuuqiKRs/7lsQoE9Ds7Eu1QmXYDrJPNELtZBV
            qbFOJubQVTf68re5Bseco6rPmf15wrXUs6LTvaQD3XUpJE52xbjIOLcYVoVYh14m
            f+6aXy+h3FLrRMi2ZvVQWQeTbeRGyqlbWGkzLIiyZv0fb4EyUiHuYKU2FTc6ehPu
            bROYx8IsjbWmiLZzkCpK/lR5ed8EFi89JYvThEh8zq+pkmRJSAx6XeKhF/4Z2kwo
            P5GCVHP/VU1VgA+Nh4x0WWhXyOSff95RZ46zE9gJKmEdSTJJKsmRQBRe2+miUmPw
            UTEIneJ9vHTGqMuSkIiVh0kskRd5Z7zOMVXy1aMNvGNGulFv/diNuuKEnlsLmI8S
            EtzrPjQDSBwuctBv74XtRVY6xvyQM8Uldsez5hSVpKys3zjlctH10c1TRUhbz4zS
            XgERPkuBMbEBNHCAFjUNJMHrdFJjc+QdP5hbUOeluChIIxBogLYeiliEQDe3vOPV
            VVv3ikUaLsaJwf+nNRkol7F7zClRYK+JjO5ygNPgy0eMe0pKx6LAzplu6nB0F4I=
            =4lTt
            -----END PGP MESSAGE-----
        fp: 4A4B9A8F518CD36766AF86DE065BDAD92D70F679
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA/haI43zIlNcAQv/f/tHlOZBOl7gyCH+vyhB36WYUjdaGQK8pNswOJ44k+97
            eAmrk/zMX7OXFONieVIeZp53OACtmzZPSjTV6jpaJlyC5rj33/pW6FAo3yqf84No
            yQ8urDNTURxe8pDjcjdOqJk837a8DBysEXZ+ih0r3exCTEQQeUkjzBqkLZv2SbV6
            viblU8cv7VXbGbLPFvyJ21EP+LfCK9BMY8CRcHPf/7qatTNDIkkiWRdKGNTxRRSX
            Cr0kMbqoS+RZABHn5fGqFiZY+crynn9g0OYyeDN9oWACwa8XYYU6GB03dhkoLGmR
            LgEtTelCGJNF3iIYtMHPfO7OiTaU8nJIQHBFg/SQipVr40ozwpn+Hl+J2aIGRTLq
            YLtEIcj8jOpmUo1yo9/DY1+RkzTQTBz62rHtZ/+bsDFJZl2pg0Wij+CQBokNKRe9
            nbNxreP3U/9SCX2ULK3KKdez0WV1MltYUvQf0BDijxBJ7OgL4DtmVsq10+5UAm81
            xZ2yPEnzgmaQqx9NNoYq0l4BGhc/KmoGmRYfdO9JqrrgbatoitGqeeCDVVWeqybQ
            9L9WFq+Pd7ZV8BDKwrT+D/GVIOif0x1mshLy5JfrCEEstRo5hQL/ultL2f+e9V1O
            XQ6+lM6PlJPP7IUMJdZv
            =bhqN
            -----END PGP MESSAGE-----
        fp: 6B9CB4956CDDD0599A518BA6CFF195C6AE9E4939
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3GO6GKnGxytAQf/SwQNFgRBpcx5zavVJDA7iUOiRtJFazK6szpGA/ZFjaZa
            DcLEYEHWsg4OTFTik2ZeEORwBEgs04SaYlPzkVGEJGYvdwezwka9Zu5OE1s6VPei
            0nfZ8tcL0+MdgS4jg4bUx5ogZ8tlEOsAWMh/9CNZQG9DUjTElDglWqZPV9cGpPLb
            +yZb/l3gxD/neYyOlBbzCkLeF9JGSXVcWCdXvVGb2aW0ReDt0qlmKkMyVvmSwa9d
            Tp7+40Esr85h1FBlPja5O1DPZfWXyiNLj/+JpUhSrIiy11wH5+7YfMoac/awJKO8
            XF0skSBxEoUmc+HNBSOiRikU0niYyvzqiAunhEfvudJeAd2XmF4EmdtjB1HThvAU
            VZTTHRI96Kp5GZ5AKQG9azH0sWg7lfBdDZ9Or3LVQcos3FrdPS5Pvkstv1pyamUw
            hx+J7ZgSqoAOhIgeRjHmfwa178PIlkaCtvcmV+H13A==
            =/3wx
            -----END PGP MESSAGE-----
        fp: 7EFB417E546C45EE36EE43F0DD2047E4342B2EBA
    -   created_at: '2020-09-28T13:51:12Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA0ZhTnV170YBAQv/U0t1va9FZH+VOaeJUQ7+3v3YowtUtasuh1i77mIJ7SdH
            QH6hmY730sX1wq/DUXSZ/TDt+TO1hzGE2tl1dmuksc59G89Cs5cmvd5epgEzELa4
            FGBuTP6xZycsy8oMaCOhGJ7M3Bon4KAiIDPKroD3LI7tDwgFglbJmhogFkCWzJ/k
            CZEy6ejbCsp+POBUu66UceJpFoMck7+V7p0Usg7r0eLh8+mgsO1Ue2ohaqwk8WL4
            m3GMgCZCiZcmTlGNMokTiEjqzNUHUYfFXmmRsOpcrNcerXpUR++gOB/5kgKWYg3/
            9BOjSSpYTLVVIqx8ipoaGj9rKiZiWOVrqafqMvrNvZSrXuts+L9xnyCM+Q+DD7OO
            gWjqX1U6R9STX3zozL26UEHSvPhTMQbSrU2sCVLX/Zx0EnMKTx0Iisp8P/IuM5A9
            Ll7m79srsvIYoxceGx5NODm2qJN83Q5M5CeCj90rVDTjL9Q20tcQ6oaFVg+u7V0l
            /zRHkuqNcnPqcDo7fCTn0l4BA17aQqBE2FmoLOVb1DvoUhm8wA1claj2hjFHSKJM
            OPJLfdavqbFIT6OygP3CRm69FznBRbUQDxbEEwzkFYyaDmv6I3Kw0NRShdTfUygb
            RHivSFZuafasV1bFVYqb
            =5Yfo
            -----END PGP MESSAGE-----
        fp: CC69D686B0FCFF3B5C2147AD8AFEC23AB1EB36A3
    -   created_at: '2020-09-30T21:54:33Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA0sgQJTuz3CvAQf/akb3yJWx6vS2T0CVLtr7u1ROjKZCVdu/NdOjULupp739
            E3eZ/zx6xvKvRCwAP2f8zppZbngRZa51HPMAIhyb6HQ1Uai6QmFFhgv3xyUKe548
            M1qpibfXe+pDv9l4NMIZw0E716RDsAhSLJh5Ni5epz5vY91L8uQ76S+GUGeOMCQe
            FUIqU2x3Z+0V+Z4OKfUupCorkT79bg5VgAkgngdq/TPXgUkoJ3tY6MWlZj/fpV4Z
            xWe8wRcpcSyPOBHz3BmtbSA+vH1zuKUsoFswEx4cbrv5CxezAsl0lHfRkfXXJRIg
            nGqh2a8oUwlvELhw+UNMLSEea8VqZyy0wTC74pjuqdJeAYYYGqIiFEGNSpt+mi6b
            OZPUghyt8wm0uUKM862BtIVOReEANiQMczo/nNgqhABMnoH+3G4UEbPaHFwbVBeP
            AZoJMEdySfLeiKPcQhLkDkSoCT1LvoAezTATnS0fMg==
            =n2vS
            -----END PGP MESSAGE-----
        fp: 84D2732F14E43B7540DF0074679ADA89F304FFB1
    -   created_at: '2020-11-16T15:30:53Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA5DboIX0e/riAQwAhw5Z1YxozCXuXFd0gBW+8lsWBPd+ctq9HF4KKMX6xhGF
            UklctN7Bdcj2QiUx2ZavBfzqKeEqTMgspc+EtPMmgLT9O8mspwEk/kEmFXmM+A7E
            nnTfg9N5bRKmodbAP+BrGhR9PsdvYcOsbOd9/T60dFs7Lem9DSZgjnakq5ypKhUf
            EmO8mfLcLxDOz9IoifIscIsauPYiny98gkaFzKhZb2UQIDePI9FAgVRYCNfZrYhF
            JFo5aEMH5XeeO3njv3dxBxyb6D7Trmy1gq+KVgwZqAeiSW73plahqVGtVlAx7cat
            0Ng9LGey5pDPWtgEEckh3evvAfABrnn2rh+TtzRUxHL8BWlD7zC0AcrUUrNfCffi
            ELFGFVN/+L83mkvYWLxBSg8azLVuKtNS/j6mIMO5EdKISEOMgfeY4apDxl9S5dZP
            09XBSOfvhzomzDOXWmbvy9P96eG3TB4VlKIESaDlHdypjtszxzj6l2Fd1GSAmKQB
            Pi03LcStDo/kibA+I8HI0l4B/mlXVhTaU7rf+63zaEddmod7Ad6Zhqy75Nw6Q1eS
            DcGdfyaxd67jYWH12ZS/E15E1h/R84gK8xId94/KjDwO/bQUZFCJdr/D/QFVAXb0
            Nw5OhaDOCs3pVHNDYAY2
            =6rpw
            -----END PGP MESSAGE-----
        fp: 54AE25FAAAF84ACAB4F1BF907696644F2069EBDA
    -   created_at: '2021-06-16T18:52:15Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMAzGezeX/6ed7AQf+O+wkPYisSBf39ynNpukc0/mOI8XtEd6m8/srdRw/Al9g
            lWx8nnpN6qASOMFoaQ8M9kP2Rs9MCvjrbD3Yu3MejbMZ2jK+c9WpEc2rdltjLwt3
            7PS0JsArpwzuxTo7VkS4lmG1Laopvcb3X6cSTduyVnawIsEGYSCo3BdmR7XguYPZ
            SfTVhe8SKpRRXS5HMXpKTYC5frWo1igzVetMVXfr9UG38Cx/trcrBFrBBlbhMMMl
            JrcobliP0KTpEGWx2uQ6n6eda0Jr5/g+n52IOWbZL23BpR0Dyaj7kaKo62eIni3W
            LLaP1ImwMWjxrJEi6NNTPNLm3qTFG0XyDvPc6ROP+9JeAXEiOhmxZi73UOJZ9M40
            NT0o+E8L6HhnA8HobYYvul+nrWWLl3zwrlovoiPD54nbLO9e/+Rp1iQzNbYFr/63
            WATo34DctuE5RCC2efkrekiQu9D3ZmxHj8huQTyhCQ==
            =bshO
            -----END PGP MESSAGE-----
        fp: DEB72DAF711EF3586266C98D9D65E8ECADD724B4
    unencrypted_regex: ^(implementer|name)$
    version: 3.6.1
