step-runner-config:
    global-defaults:
        container-registries:
            registry.redhat.io:
                password: ENC[AES256_GCM,data:hUGQXK7U+RYx90y76RrQmnFkcKh4RYKOuzktBnwm/OdiTyvoz8XkW2CHzvH1fqG0Z1wnCvW4FbmwXuBnFCIMjFX/r39KBEV5tsli3pVeSU61yULf+ZKHNFL8t8SKw9wqeAHnftfs11qoTjBvVdK/ktuldfgkASTBCvdFn8I5WHZEwzEADYkR+Ln+mVxs9K5NELhJcoOyhQPo98EuP3T26Wp1jdSS2nbA+HDJoQvuS3HX8dKN04Dctx+nxCjiZMkueuOxjLnLdyfRlyRt1tTNOUx6DBv5qnMlugLKDAjNQ52GnQYSXG4Bcuq/0OvUPLxVgt+dPK28kI60PsssBlzVyAPCpX31913+5v8M/05T5K2/NB6xRjQ/SVCZMjj676vIG3SUFWE2YxS1wuvWv2jhGaB0+lx5VObHVEoWm0sTTPtYc7Zb5mCu7Mkh/gfkyV1VDXtC6hYF2m7vIn55g6GZZVf3VtY/4niwa4NtUNbzPq+oc2mLB26CUykflXFL0IJ53zOMbohBZPX6f8XKjteIaPQVUScMJl4BlWds03wpxaL4aO4hxSAzdQxKcgcFKGztP4wGl5+vzwQz+bQr+SMz/12G4BrLfIZWk51Wk81JxmMqBoRYb9GVzIHRRaBPn1H0GbJL6QfEgZX7SpcV38Cs6OKzvuJbU1TgeWjPn+KmgwTt5cC7c0BhUvgLzsq2gA+5UBZif/dHHYZQbgOVMLgT6Cxd62EojkT+wpO4yuRZUAgSc9wMN4GA4WZCmof8e0mUHw0qifsp8jGDwTY91I/4EKYEEBiESfedWE0oOaWD8mYX3TM4qlSMSsTvE/gh3Z/JBT8VhEV2RgJlFGSJbG1porCY+FqlSZNpVBSXEcOTgGudb2Ig3aQ/RtFQTKI6FlspXIQEYISquQEnOdAdc/XlDV569L0kkVNDRMe5VO2jH0fakCumsydIl1kCK7R8x4t6C2EvdhutArQfEqsEJynv3M35gWoQ8c8X59tbc/uSPBT2mA0qbUcGyeM=,iv:CToBAR7LCzZFLWBYxlwKxRHjFeJCO11DHqZAgWKY6ZM=,tag:NszUFOGdAWv1blRpOGT4/w==,type:str]
            quay-quay-enterprise.apps.tssc.rht-set.com:
                password: ENC[AES256_GCM,data:tcULYxxKu843I0OgP4X58XjJVwSqhu9N22AnhlyAR3Bk2hXzTjutmUIvK9To5cnB0EDgXX8w4nGRPboeNrGe/w==,iv:ybic1Pe0pmaiDlYzZL3wcWqmgY0rHIGv6aZeo2AfC78=,tag:kQuyBWtmxK4KcoU+HnNScw==,type:str]
        maven-servers:
            internal-mirror:
                password: ENC[AES256_GCM,data:NWWmc0/SL7Xw7bN2gU9UxGsQ,iv:IxYdTRjp79l8pVX2VnffXoo1pVp/Stbp4+5Ot8jB7Q4=,tag:tG98HHLBGTUWYzns4VvS3g==,type:str]
    tag-source:
    -   implementer: Git
        config:
            git-password: ENC[AES256_GCM,data:QskmYKk1CzuMiluo,iv:RaTfe/DyTH9SqQUFoZ9O5Hdl0HGQ3YT8LKuTyRyC3wM=,tag:4DgsjcJE7tOShZNojVSu3Q==,type:str]
    static-code-analysis:
    -   implementer: SonarQube
        config:
            password: ENC[AES256_GCM,data:vTevnGUx5pooROpBff3flA4p,iv:IUsyBh9kD1ME3UM2r8xKarHnP9ml9hcG/+rM0STxTFA=,tag:Ju8CP/dS8+LptIA7die5Ew==,type:str]
    deploy:
    -   implementer: ArgoCD
        config:
            argocd-password: ENC[AES256_GCM,data:VpbbTRg+,iv:C0uuG7Qcq0APBWQ1h9vc+bG3uIyCpKDarv+VIaTVNXM=,tag:6dG/HFq66bFLdqTUoRjGmQ==,type:str]
            git-password: ENC[AES256_GCM,data:x3qaCvzIAEsu/2aU,iv:6lh2/+sT1wi/g2k0mCFAF0AmNH/YPMkIoxlBgGrAfQw=,tag:wGC+pJDeRb1BObHCAJllNA==,type:str]
    report:
    -   implementer: ResultArtifactsArchive
        config:
            results-archive-destination-password: ENC[AES256_GCM,data:n2bhqCvyEp/Wz2Eu6t26vy7m,iv:/YLeh8aO7z6hEGaFTHgyyFpSsFbr9aB23botWwe9qrs=,tag:GjmS5qVMvq6MMEplSfTV8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-06-30T11:58:55Z'
    mac: ENC[AES256_GCM,data:sgRQ1QLqMbBYVQBeTWQqvR+2TJ8gkS9Is+f/6PzQVskWkkwbpQtDhdDwfEgLhT3pZwbcssDLT7pSVwZn5P1BZRmi7abuX6qe4i4chaZghRyLPTH+ZPRywj1+ArxLzalg628xNCARImFJ+IWIamsUXtQSDk8wCc1ROBZNzD4H+B8=,iv:MCUO1oAYgCOsygXoKs967pZ6MPMUa4TfZY4pXQxiJkA=,tag:RVuUb9ox2blwkClinQzJwQ==,type:str]
    pgp:
    -   created_at: '2020-09-28T12:23:20Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3GO6GKnGxytAQgAkLDVO+6ZPplI2ND8H3PPfDq3MReMCcJ/BnFuEUFw++Om
            ZX7b587qpfO+pc1BUfQveC3wrZbJAAJF2zg/bN7nr7OvooygawOD4Elz9NsrEowZ
            v1Rjw5oB4aVDtqYbEiCmQWl6LmeY9Isi0FdSDVyAW/C4rJIyZlJL8AJ9ThVeIMwG
            6zHeNabh9zviijomoyNDfvrvqP8XTzOVsLs/4fmmek4IS735gW9P0p2UMBOMf7/x
            2z6dcKyHs/zMb6xO28HTkRM3aLuCX182y19xjAX9XW1pNlmgBIiTgR3+To+Wy5Ow
            Jf4nrFtXP2wbTmpJk16chhb0eA9Iz1MMpI2uXeeOVtJcASwPlf7S6eRQquWDQgmp
            qxwgpkmTVwHcOltif+2JZCmFuelCF3XTFrXM366t3aSdr9kcK4CpbdDRuPZl7sXv
            Rpi6BZGOTjhIsp/oVmo/0EuqTuMnLkOKastoq1c=
            =P0/M
            -----END PGP MESSAGE-----
        fp: 7EFB417E546C45EE36EE43F0DD2047E4342B2EBA
    -   created_at: '2020-09-28T12:28:18Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/pHJVB+8SuwAQ/+Par8fTkoUd57LpSB/37YoTCaD5ZOYju2Rz30MeVdiJK4
            f840kn+6hN1mGZqdmEojZCARABL4w1gIzZHjsC5RJzW3E2OZn5sepDVlQf/0+gD2
            INeduhvk9U+HsUmdgGKJqv2MfydgZCYcshQgAV+vzqBZOe3Z5ZXComy6B+6vdyEF
            ZNl7N/gJzAzdarJbDCJ7n/n45GPQpncDZnjNIJ07fhUSEb1lxc7Zzt6O6bdwPh0k
            JvOF8BN9qvUIBpr4yoNHp7JGCUK+5Zs3HVzrQYSauepxw6pO8WF+Zrz8MH9HF8EM
            hR/VAFFRH9TYGB0MYESibhZMekL+ZaAc0euujOyfQRzSPryM9xmAOEYQL0gQUPJJ
            qpFX2eZVZIiLP1pEjAyTHZ7WCTq4Udtza2juMqJwqXvJaPeeqcs1y1OJ/7UaWMqi
            yTwxe0h/UAUVkhBdJmXjttC4bhJF3XJYJECGiISGG+fjRTX4cafaCaOY2tytRIOQ
            Y3nCguqaHrxQXRfqcJFoJnQxELEztKEueASxxtKljMnDc9vkJgLMSHLqhHc2SLbC
            oflITcQ3rhTH4zv9xHvG/6dct2atP062JwAnuCwVoZIaPmHtd7rCxi2l/QDN69Xm
            dL638H7SUgbPoh7zD3vSPLaZOGbaUsX7Z0zYtUxJS3E/gO5DRDcC+sgynW1/fY7S
            XAFeSeJ023RYd7V3I+TJf0glrKYHWjVfUnWz2HAB2Gda9tDYBIZUvQe3UkKP1WrW
            c9EIOpPsVuHCokwDxYGPQGpcVfPon+3BbdczGpbYgZprcbXojY5n8HqJfhx/
            =kJ2Z
            -----END PGP MESSAGE-----
        fp: 355C11B55E83B15E5CF6366283637FAF9D7905E1
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/JEnAHZDjB7AQgAr/d6tyGCT7PekPPK+KPT7pl8IWIx1DrWDyxFJqKGRhpT
            sGqsyKW/jCRKgCSi97VM1/xAKgKS51NYWUpFNIj/63qPjLN2x5h4matXv62jDTWY
            /cnI541LPfxO4x6AoQ3Fa6puhVZA8PIT6Y6MxVst1MuUs1wqZvmO64hqg4zS7VfX
            Mx7Qficy8w4LgqyI2A3lADnbePFfbSHSk1KXOo4DGCcjJefdaROXoJqHwo4PUZ1K
            yxKrZRXXyCovO2hqEi4RLcSHp3KpTuYadQy1Gmkyy0MPCofrUmM2F8mBlRiXiAo8
            EIin/V1sSzSy7vAoWO1RcozubCD/y1vakg0fuQDdDdJcAebuzg10ylUm3oOyT15e
            o4XATHv/xXEusEEgJ/5H/390g8Gnc1fiR8Y50GQxoPg2XruTjSShaIb+5wcXe6Hf
            3b+pTQfCJ5dM9bd872X33o9I9Hu3AdU2Mr/AO0Q=
            =vE8q
            -----END PGP MESSAGE-----
        fp: 2A25DA15018235A6206921952730D7A70EC35190
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6220UozeaaQAQ/7BgQrPsee5G/tnC8qSriZkAWZvQ+kxlg9eDHHFi/S5VAA
            Mn38GeQKEzeJvfLOmxnB0RRX6nkRxoS/OQFBPemVEiobFPKRSXob1NYmoI7FdkF0
            0WJpaL14GvChiJav0kXSj29v/UKeE8IBpID/4TO4ZQ//DCPH8eETB+1mQXaPlYBA
            WHkQvCZ2cq6RvsLKKlz+gFdn/0sgpRqW+YApoubM4qVjWGowvUKu5cAlhu5oE5C4
            jAr2vRQTGdiEekjm/2nw5Fj/ZRpLOATnqhInrAQ4a//XdEC9gbljjeWtz7+ju4nq
            uCRHpFVwpJQIrGC4IIdfs/hunpmaWGOjhOzXcB4QkxvDUT8dczPuHVgVg9jSC8Iw
            RcVJXieL4jNLUtg6Tt2U0GSO7leVusSnGEHb76tMeTjWiUebyowZ4C6ynCw4DA9a
            IFmpjcMu8lnawqMtU1kyHBMrNLFTwmgQ15me/BrIYlOq4zBFVeZbfkfqYtzgwoez
            QubmvG5N0kn8Ru4MLBPbuZ7JCyzP/HXXElUYAouLdMwjDONmi9bIHuSynfspsOL7
            PCq8KXVPDt2IMHRVP3ygk4y3zYk//QESZczT1ivSBTAbMSRYsdUVZFI46czecLrp
            544zpbe455H2bmHfSca9jnLCp6ErJSxf1IO3fqUJTOEErRcMtOQTQ77roeHVq+jS
            XAHpznC4yN5wlsaiC0g+6jC+B8dtAJdGDsSRQrNn2DQ51rIzBWsWwYSewh8jovy8
            QhrUpyRpi5ByY/TjdmrBCGu0hyDsODdDCHMgRunzE6Cr1OLRL2bzjixnl7LT
            =UcR1
            -----END PGP MESSAGE-----
        fp: DA7B00C8ACAFED2DA7E33D1ADFA8C968E1F69B13
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA75NWiDtWcDHAQ/5AdWtFkCe4yBeewT+6eQ/Qwi5yLP1dyTUf5IWMKrNSzcv
            5nEfaMMmAgP8ByrbPlCLKCL1qmuxVfGXCMkB5lGWk/tg4biN6JItEpP44exvEaQr
            6Wn7hWVxYtJfpvVE2niqRRfugWnOg7th8QUkfWucZtbi1Ag+BhM6lD064PaQunMW
            8uq51JGWHRorD/FLlM0ssNj0h1GmS7pLyXtiiJiAi1lHXW0iRa9vVk6l1LvP1YM5
            44LZJyeviExBFZKE/fyxOke1Jaqmfd2XHujO6t64u3xoT3H3ywUOc0Q1dEYmsED5
            itx9SZVOS+F4faO17MfIE/rjLsBWqA6uEP1NijFKah3ovjn3evomFnv9Yslgf4v2
            F01pS66ByF3zZyYmbDtYN4MfoGics2FxUxU3c0hLXm1X7W8w+lNWsy7jVnH2xdYZ
            7EeGYe53ODvf7HP+vQQs8AaCIjJbs61XlMvkQJKLZdd4zRYAuUScen9aGUujpDHZ
            Aq7gMCKmBj82V3nwdOYu0hCY82X4NGEEvzPaqQBOC8nRGInzWSUBEYzgnHSle81c
            B4jLWImzOnggE5ug1MBVIjW22dmkB6LiaXry3nIxcC7q4Yo5Jw7QrKoJx9TLc25B
            MZ8O+pWXcFNA2lcXOKwPm6W+r1feM/r2q7YzFlP8eqiHXjpbV+bFwN7SetBeGivS
            XAFMedqeyH8atp4Ffo6rWQ9ypwWrcIZpX4tVpXanE2EL2c4vlyqjkJP6EuDVRFbN
            r6e4uCwxhbWZgC9B9hvY9Veq8vf+5vkNgoQPRSpdGYprlhuSLU4OlQo5HUQ6
            =HWcc
            -----END PGP MESSAGE-----
        fp: 4A4B9A8F518CD36766AF86DE065BDAD92D70F679
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA/haI43zIlNcAQv+KBGTJdWszLcPEyMpUhcue0YA2Zs0s1+cvzW2IRPCjCMf
            vOWXihIKhz3k/irMcq5UbL+CyXo8S28iJ9p9Q+FPqvbiZUXd/rSjPiV+67UjyDl4
            BIf75mQ4oJLIoFPM7Fu40nEqlyApWqtr/Fo1PPlSMGtnJtkgJu1UVYlvVQm8E1EJ
            R9KzdhGpY4jtX2jVmAWmmJ1Q9UH5SycZh9f/EVw8pQkMQZhEJMN6aeu/2CFbdaZl
            UtVeokQlcmd69EMwJsOyLDyCcepPk9YdY9kHYniBc8rbBwVzYr3aVnhu39L+skSm
            jdxTqjJvtsN2JlNCPejHlwwTcDV8k7X/2pwa+vHqURY6Lj/vAv8fnqEAeT/STA1j
            Ig1k3SRNa5jSueX+u1Uy0o5jo5WhflyGrs3jB85iCc9d1P5QE7BfcaGXNFfZ543B
            FHiUEUzcjTrUc3IzqEhxtav2Dk7mkoq4+2fuowrjvYljtL4hC2QEsOPY2UNX392i
            wWW9wyeRxlU7+lsKrLpp0lwBtQpNineL/+jwvKhBJVrTcd4szN3pj8PQ8TQPc88n
            T979krODerCWBu0Mf9FhfcHBKAUA4G11iteyLnoqmPR+rS4WaGWIA55jzQcE6jNc
            2+XXPdFfsJg8romn1A==
            =LRej
            -----END PGP MESSAGE-----
        fp: 6B9CB4956CDDD0599A518BA6CFF195C6AE9E4939
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3GO6GKnGxytAQgAo10TPEkbmAn9yeJdokybkAXVaU2vxSgUgTTMDNq131vg
            YSz95NV5KxvEOEVZNVbo5K6xsKR7coLcalTkqbqXp3/wKscCIiVwhZ4M/wKybTbS
            7N/caLfV/PmYkBO+FatmpmqwPfRBmT/MM0KLuUOoibhA/zfo00dkz+z1d+I5HAl4
            DjxJiMQSn+BTPFdn/VsbMKOr7bcuId4jV5TK4gBqaD3n3B6vrCeXmW4a37MpreRD
            FaI0XVWumk6p0OtvQZigvqkArkDLxJndctahS5OjgvSLeitHkVIheHNZLg4MDXbJ
            aVdSI0BMI6+Id8j0iFk9NnjsEgPjLWEKOR6dabQ2I9JcAcw2DYLM5xNuZN345KYu
            v6QdAMMWv0Zb6s0TrjSlYaBRDhBFAF9mJJ3dRfgN3jy8j0RkK679Ei6kKuGUytQJ
            +hnivzzc+VzTXwxt6liFh5iX5BrE5lrdmo0HB7U=
            =Ia+C
            -----END PGP MESSAGE-----
        fp: 7EFB417E546C45EE36EE43F0DD2047E4342B2EBA
    -   created_at: '2020-09-28T13:51:12Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA0ZhTnV170YBAQv/aq5oWM2psaQ0GRabqySQhniiWAXs8gPfnY3CHVNpetMh
            +8AdJLueJbGn99mCzpMTaukTuIf026Rj4An6NZkATE7cdhODti8xcwngVsXmRApf
            jX+ehLDM1xehbXWa4JYIHAMTZtJi4iokEfw+C29q8MctcsjATNX2uuzvYRRuMElV
            FE3b5o8kBzA/TUBUcVBRG3hO+eFQuy8ELluyxf520qA6pzeGixBiw3mvaWKVQ/J2
            Eebd7YnxSjKrkoQmrliwCAaUFfr0XJMhRIAqwgiZkJdfrP1JKGorMbCFdduIPCgK
            /ddcizbtKPBmUzMZbo8M+3LRNcGLmlIbgJSixnSzpds/NcarjhUlT6FbsWbXMQtJ
            7wtdP3W9C4jOs+RIyFGQ/BDAFmOhjzoJ+UwCHGid6U76I4H5RHetWraOLuM1kf4F
            RG0xWkroOxh6Vxk00YTWezjM3sJQipZXlZUDUYqXFeNZegpTpIP43THpebZU+rrO
            5Ihr/OHAle42VgICOzwB0lwB2qrQ13mii0Mkgoiz0/3h1wsJ5mljlOXGaiJZ9sXu
            Np3xGp1hFnxyRm8ZnqVEX/6Lxaq3xJLIq7Mb/39/jQxL/YtIMkNyPWzK2GStsN0n
            Q2pH1anktt9qEB7SOg==
            =3Gwb
            -----END PGP MESSAGE-----
        fp: CC69D686B0FCFF3B5C2147AD8AFEC23AB1EB36A3
    -   created_at: '2020-09-30T21:54:33Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA0sgQJTuz3CvAQf/Q4BgHr82cq5TKPNkt/xy3jswtccAfUEdFxYR1ZkrOHZO
            UOA/IdwHY9fVtwB0Ij/kERBiURi7JQoc8IqKNb+/azm/XslEO6RxWmmDC2wRaL1B
            5KBp6Psrupa2Ug3fdxbwfWgzkB1uzQny6AU4c/o39DjB96lcxq2lgzl7Z1ao/djk
            D4yakNj0YGqdFOHL56/lbzEc2dzgIA+fzlnz75pPl9jLvntN8EONqi+3yVhcQ4iK
            vLJHKG2BiY4IeImOPGxQQ5o7U2CFHopiHlNCoaBkx1NQBdjbZJ6HoFsLHeYOVfOP
            6sJATWv5eLp3TcqdTHBBbH7swCIK3VOy+WLQNnzvi9JcATAHWe96lftGgKo58rZa
            J28r1EERYs9+8q97DJ9butI6sI2isJZqXo2G/9ywG5Eu+H8G6SLSbnRfkQcz1a30
            8C+Ux8piKvz2Y9nBh68LHKQWtaBT+HnG3UJplvI=
            =dqfZ
            -----END PGP MESSAGE-----
        fp: 84D2732F14E43B7540DF0074679ADA89F304FFB1
    -   created_at: '2020-11-16T15:30:53Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA5DboIX0e/riAQwAqJyzy10QgIHiFi+9VoBZYcmCWuO/CfQBP82VJZvvwRsa
            bqXvxQQPRDJ7cxxkingf8z4dCZm1ZSd9DFXwFCuXAzyOLJ4I3CoGwRyY+/vnG5RC
            jcKCnqR8hVZFOTMOzmDE7iQnMSe2AVW32i/zcmx3i1WyrnKoZa2MuhHLA1c5uxYD
            nWKbsgoOjU6KYPOgDIpn8VX8+D7MaUBe+3vqJ+ko6Z++VdgdeDTlPcswz2P82Ur2
            KQDsi+6vTgujb6J8kinl4iG8JDlMXBoKUDGeRcfio4heJ5nsjb7TIW1Dg31x4KE/
            kUEcyaxcttiInjg2nqqiQSTw8pEIsPUHoK8OSCl9+n4tW6hguscFqOnaNNZSwSjp
            6/G3lEEe4u35busG9ukWjzzvWlHYU0y1NF3oGejQ1MzUHRbM21SiwvqpXmmXxsk0
            xxHW8FFPlgRdYdze+I1gA6JqXm/UWLOlNzMo44oT0XxH4S5PayUrDHSThCVJ1edu
            q6fcC3f47BlvpzK34len0lwB+anRKN0XsUh1VU5pDQ/+W9uqPJXYAiMRz4K0Cmlx
            OukYTCmdNgHsAh2V1XIDZYcRV42mo7XQaCHBVybRHVMilXo6dUews7PhstVjeUAD
            72jo7bEQyni29QIFDQ==
            =XmpL
            -----END PGP MESSAGE-----
        fp: 54AE25FAAAF84ACAB4F1BF907696644F2069EBDA
    -   created_at: '2021-06-16T18:52:15Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMAzGezeX/6ed7AQf8Cs8Xjob4akcnsCE57AGtMVmYUGZo6yfLLBUmsexZd3ev
            iyeGZdnOCD6ibyLBt4oJBvxVxFflskshtV3qK1N8gCxU3cs7NjldZxLQKg/TYDrE
            GvPSSfY+BdQcWK68cQ0huRd5Cq019QOX9Xj+hqCOPtiZ+QbdNHuN0gCbwAdeJ3vq
            9vXbWV91fcJEGsREVlcGIb4Ywe5eXoP/Sn2uvVcCs2bqSE4xx3Nz3iL4P6kiqF9t
            UBIz8FvL6pgX/6N2rfeaqYT/OyP+kY893G/x3kqexIxdswDc63d+8Ze2bgiOh2If
            35gQf7Jq9J7WcpnWONl7EKAhyoohxrztjitroZsV9dJcAbLrzwuiZCKuooM4tl5g
            ZGFPne3D0fNKy2iz9m925wtRBf4IT7NItMavWs9tG5m67h7ZqlMhjCmmMMqhuZt/
            LotNxQ91dAz6NbOiG0Fv/yHYVtYLWXHCjgbAh5Q=
            =Pezk
            -----END PGP MESSAGE-----
        fp: DEB72DAF711EF3586266C98D9D65E8ECADD724B4
    unencrypted_regex: ^(implementer|name)$
    version: 3.6.1
